# Generated by Django 4.2.4 on 2024-06-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0003_alter_medicine_drugid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escort', models.BooleanField(default=True)),
                ('patient', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['Escort'],
            },
        ),
        migrations.RemoveField(
            model_name='escort',
            name='ProfilePicture',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ProfilePicture',
        ),
    ]
