# Generated by Django 4.2.4 on 2024-06-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0004_usertype_remove_escort_profilepicture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
